"""Added estimated_home

Revision ID: 0de579236cf0
Revises: 53a89f511064
Create Date: 2025-05-07 10:16:13.074593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de579236cf0'
down_revision: Union[str, None] = '53a89f511064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimated_home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('kitchen_area', sa.Float(), nullable=False),
    sa.Column('living_area', sa.Float(), nullable=False),
    sa.Column('is_apartments', sa.Boolean(), nullable=False),
    sa.Column('floors_count', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('rooms_count', sa.Integer(), nullable=False),
    sa.Column('building_material', sa.String(), nullable=False),
    sa.Column('elevators', sa.Integer(), nullable=False),
    sa.Column('balconies_count', sa.Integer(), nullable=False),
    sa.Column('has_furniture', sa.Boolean(), nullable=False),
    sa.Column('compute_date', sa.BigInteger(), nullable=False),
    sa.Column('computed_price', sa.Integer(), nullable=False),
    sa.Column('similar_objects', sa.JSON(), nullable=True),
    sa.Column('graphic', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimated_home')
    # ### end Alembic commands ###
