"""Initial migration

Revision ID: 68c30a337e55
Revises: 
Create Date: 2025-05-01 14:50:48.914876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c30a337e55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

initial_cities = [
    {'name': 'spb', 'id': 2, 'name_ru': 'Санкт-Петербург', 'center': (59.9390012, 30.3158184), 'is_in_model': True},
    {'name': 'moscow', 'id': 1, 'name_ru': 'Москва', 'center': (55.7540584, 37.62049), 'is_in_model': True},
    {'name': 'nsk', 'id': 4897, 'name_ru': 'Новосибирск', 'center': (55.030204, 82.920430), 'is_in_model': False},
    {'name': 'kazan', 'id': 4777, 'name_ru': 'Казань', 'center': (55.796317, 49.106092), 'is_in_model': False},
    {'name': 'ekb', 'id': 4743, 'name_ru': 'Екатеринбург', 'center': (56.838011, 60.597474), 'is_in_model': False},
    {'name': 'krasnoyarsk', 'id': 4827, 'name_ru': 'Красноярск', 'center': (56.010543, 92.852581), 'is_in_model': False},
    {'name': 'nizh_novg', 'id': 4885, 'name_ru': 'Нижний Новгород', 'center': (56.326797, 44.006516), 'is_in_model': False},
    {'name': 'chlb', 'id': 5048, 'name_ru': 'Челябинск', 'center': (55.159902, 61.402554), 'is_in_model': False},
    {'name': 'ufa', 'id': 176245, 'name_ru': 'Уфа', 'center': (54.735152, 55.958736), 'is_in_model': False},
    {'name': 'krasnodar', 'id': 4820, 'name_ru': 'Краснодар', 'center': (45.035470, 38.975313), 'is_in_model': False},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('cian_id', sa.Integer(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('is_in_model', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cian_id'),
    sa.UniqueConstraint('name_ru'),
    sa.UniqueConstraint('short_name')
    )
    for city in initial_cities:
        op.execute(
            f"""
            insert into city (short_name, name_ru, cian_id, center_lat, center_lon, is_in_model) 
            values ('{city["name"]}', '{city["name_ru"]}', {city["id"]}, {city["center"][0]}, {city["center"][1]}, {city["is_in_model"]})
            """
        )
    op.create_table('metro_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metro_station')
    op.drop_table('city')
    # ### end Alembic commands ###
