"""Deleted unused fields

Revision ID: d63d7c9c5359
Revises: 0de579236cf0
Create Date: 2025-05-12 19:13:59.996906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63d7c9c5359'
down_revision: Union[str, None] = '0de579236cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimated_home', 'graphic',
               existing_type=postgresql.JSON(astext_type=sa.Text()))
    op.drop_column('estimated_home', 'living_area')
    op.drop_column('estimated_home', 'kitchen_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimated_home', sa.Column('kitchen_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('estimated_home', sa.Column('living_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
